repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.246'
    hooks:
      - id: ruff
  - repo: https://github.com/nbQA-dev/nbQA
    # Run ruff on Jupyter notebooks too
    rev: 1.6.1
    hooks:
      - id: nbqa-ruff
      - id: nbqa-isort
        args: ["--float-to-top"]
  # Spelling mistakes:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        args:
        - --unsafe
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --unittest
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(.+)(?<!\_version)\.py$
      - id: black-jupyter
#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        language: python
#        types:
#          - python
#        pass_filenames: false
#        entry: make test-cov
#        additional_dependencies:
#          - coverage
#          - pytest
#        stages: [ push ]
