coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Target total project coverage
        target: 70%
        threshold: 2%
    patch:
      default:
        # Target coverage for changes in PRs
        target: 70%
        threshold: 1%
