{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: ritme
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - importlib-metadata
    - qiime2 {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - q2-phylogeny {{ qiime2_epoch }}.*
    - lightning
    - mlflow
    - numpy
    - optuna
    - packaging
    - pandas
    - pip
    - pytorch
    - python-dotenv
    - py-xgboost
    # todo: update ray to newest once Q2 has migrated to Python 3.10
    - ray-default==2.24.0
    - ray-tune==2.24.0
    - scipy
    - scikit-learn
    - scikit-bio
    - setuptools
    - torchmetrics
    - torchvision
    - zipp
  # TODO: build package from GH or pypip
  run_constrained:
    - pip:
      - coral_pytorch
      - c-lasso
      # grpcio pinned due to incompatibility with ray caused by c-lasso
      - grpcio==1.51.1
      # to enable insights in ray dashboard
      - py-spy
      - typer
      - wandb


test:
  requires:
    - parameterized
    - coverage
    - pytest-cov
  imports:
    - ritme
    - qiime2.plugins.ritme
  commands:
    - pytest --cov ritme --pyargs ritme

about:
  home: https://github.com/adamovanja/ritme
  license: BSD-3-Clause
  license_family: BSD
