{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-time
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - pip

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - scikit-bio
    - ray-tune
    - tune-sklearn

test:
  requires:
    - parameterized
    - coverage
    - pytest-cov
  imports:
    - q2_time
    - qiime2.plugins.time
  commands:
    - pytest --cov q2_time --pyargs q2_time

about:
  home: https://github.com/adamovanja/q2-time
  license: BSD-3-Clause
  license_family: BSD
