{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: ritme
  version: {{ version }}

source:
  path: ../..

build:
  noarch: python
  script: make install

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - cmaes
    - grpcio
    - importlib-metadata
    - conda-forge::ipywidgets
    - lightning
    - mlflow >=2.0
    - nbformat
    - numpy
    - optuna
    - packaging
    - pandas
    - pip
    - plotly
    - py-spy
    - py-xgboost
    - python-dotenv
    - pytorch
    - conda-forge::ray-default >=2.54
    - conda-forge::ray-tune >=2.54
    - scikit-bio
    - scikit-learn
    - scipy
    - conda-forge::seaborn
    - conda-forge::shap
    - torchmetrics
    - torchvision
    - typer
    - wandb >= 0.26.1
    - zipp

test:
  requires:
    - parameterized
    - coverage
    - pytest
    - pytest-cov
  imports:
    - ritme
  commands:
    - pytest -v --cov ritme --pyargs ritme

about:
  home: https://github.com/adamovanja/ritme
  license: BSD-3-Clause
  license_family: BSD
