{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-ritme
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - pip

  run:
    - python {{ python }}
    - importlib-metadata
    - qiime2 {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - lightning
    - mlflow
    - numpy
    - pandas
    - pip
    - pytorch
    - py-xgboost
    # todo: update to newest ray-tune version
    - ray-tune==2.6.3
    - ray-default
    - scipy
    - scikit-learn
    - scikit-bio
    - torchvision
    - zipp
  # TODO: build package from GH or pypip
  run_constrained:
    - pip:
      - coral_pytorch


test:
  requires:
    - parameterized
    - coverage
    - pytest-cov
  imports:
    - q2_ritme
    - qiime2.plugins.ritme
  commands:
    - pytest --cov q2_ritme --pyargs q2_ritme

about:
  home: https://github.com/adamovanja/q2-ritme
  license: BSD-3-Clause
  license_family: BSD
