{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: ritme
  version: {{ version }}

source:
  path: ../..

build:
  noarch: python
  script: make install

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - grpcio
    - importlib-metadata
    - qiime2::qiime2
    - qiime2::q2-feature-table
    - qiime2::q2-phylogeny
    - lightning
    - mlflow
    - numpy
    - optuna
    - packaging
    - pandas
    - pip
    - pytorch
    - python-dotenv
    - py-spy
    - py-xgboost
    - ray-default
    - ray-tune
    - scipy
    - scikit-learn
    - scikit-bio
    - setuptools
    - torchmetrics
    - torchvision
    - typer
    - wandb
    - zipp

test:
  requires:
    - parameterized
    - coverage
    - pytest
    - pytest-cov
  imports:
    - ritme
  commands:
    - pytest -v --cov ritme --pyargs ritme

about:
  home: https://github.com/adamovanja/ritme
  license: BSD-3-Clause
  license_family: BSD
