{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-ritme
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools==69.5.1
    - pip

  run:
    - python {{ python }}
    - importlib-metadata
    - qiime2 {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - q2-phylogeny {{ qiime2_epoch }}.*
    # todo: check if q2-types is really needed - if not remove
    - q2-types {{ qiime2_epoch }}.*
    - lightning
    # todo: once newest version is passing all tests: upgrade mlflow
    - mlflow==2.11.3
    - numpy
    - pandas
    - pip
    - pytorch
    - py-xgboost
    # todo: update ray to newest once Q2 has migrated to Python 3.10
    # note: currently ray is in v2.8.1
    - ray-default
    - ray-tune
    - scipy
    - scikit-learn
    - scikit-bio
    - setuptools==69.5.1
    - torchvision
    - zipp
  # TODO: build package from GH or pypip
  run_constrained:
    - pip:
      - coral_pytorch
      - c-lasso
      # grpcio pinned due to incompatibility with ray caused by c-lasso
      - grpcio==1.51.1


test:
  requires:
    - parameterized
    - coverage
    - pytest-cov
  imports:
    - q2_ritme
    - qiime2.plugins.ritme
  commands:
    - pytest --cov q2_ritme --pyargs q2_ritme

about:
  home: https://github.com/adamovanja/q2-ritme
  license: BSD-3-Clause
  license_family: BSD
